### ISSUE TITLE
Legend for connections. 

### ISSUE THREAD

**Issue by josedeone** [Samantha-uk/zigzag-v1#5]
**Is your feature request related to a problem? Please describe.**

First of all thank you so much for this code, it has been a life saver. My only issue is that I can’t find for my life anywhere the legend for the color lines in between nodes. I have different colors ones like red, yellow, orange and green. I’ll attach a screenshot. In conclusion all i need is a way to know what the lines mean. Thank you on advance. 

![7631BD84-D88D-4AED-AF88-CEE442B6E251](https://user-images.githubusercontent.com/39321687/97069807-bd4fb400-15a0-11eb-8222-c545c498297a.jpeg)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by boralyl** [comment]
I think this code should give you some context: https://github.com/Samantha-uk/zigzag/blob/master/src/graphing/ZagDisplayConfig.ts#L2-L14

**Comment by josedeone** [comment]
> I think this code should give you some context: https://github.com/Samantha-uk/zigzag/blob/master/src/graphing/ZagDisplayConfig.ts#L2-L14

Thank you boraly. Much appreciate
